0-world_wide_web

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -2,17 +2,27 @@
 # Bash script that will display information about the subdomains
 
 dns_config () {
-    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
-    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
+    local domain="$1"
+    local subdomain="$2"
+    local dig_output
+
+    if dig_output=$(dig "$subdomain.$domain" +short); then
+        local record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/{getline; print $4}')
+        echo "The subdomain $subdomain is a $record_type record and points to $dig_output"
+    else
+        echo "Error: Unable to retrieve DNS information for $subdomain.$domain"
+    fi
 }
 
-if [ "$#" == 1 ]
-then
-  dns_config "$1" "www"
-  dns_config "$1" "lb-01"
-  dns_config "$1" "web-01"
-  dns_config "$1" "web-02"
-elif [ "$#" == 2 ]
-then
-  dns_config "$1" "$2"
+if [ "$#" -eq 1 ]; then
+    dns_config "$1" "www"
+    dns_config "$1" "lb-01"
+    dns_config "$1" "web-01"
+    dns_config "$1" "web-02"
+elif [ "$#" -eq 2 ]; then
+    dns_config "$@"
+else
+    echo "Usage: $0 <domain> [subdomain]"
+    exit 1
 fi
+
